name: Commit Updated Projects

permissions: 'write-all'

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Run the script
        run: node scripts/syncProjects.js

      - name: Install vercel
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{secrets.VERCEL_TOKEN}}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}