name: Commit Updated Projects

permissions: 'write-all'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Run the script
        run: node scripts/syncProjects.js

      - name: Install vercel
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: vercel --prod